### ISSUE TITLE
Won't start fine-tuning with tensorflow backend

### ISSUE THREAD

**Issue by iamgroot42** [danielvarga/keras-finetuning#2]
Throws the following error as soon as the images are loaded:

![image](https://cloud.githubusercontent.com/assets/10141323/18320487/b13ce00a-7547-11e6-8da4-0a6d2e5f1487.png)

Contents of keras.json:
{  
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}

P.S. : Even tried replacing 'th' with 'tf', but I guess the part causing this error comes before any difference between 'th' and 'tf' can appear.

**Comment by iamgroot42** [comment]
This was a problem with the Tensorflow version. >= 0.10 is required.
(Though even after that, new errors such as `Error when checking model input: expected input_1 to have shape (None, None, None, 3) but got array with shape (128, 3, 224, 224)` pop up.

**Comment by uros-r** [comment]
For the shape error, simply reshape to conform to the TF backend convention, e.g.

```
X_train = X_train.reshape(X_train.shape[0], n, n, n_chan)
X_test = X_test.reshape(X_test.shape[0], n, n, n_chan)
```
